name: Xprex
favicon: null
layout_spectrum: 0.72788
typography_spectrum: 0.48915
title: 'Xprex Intelligent Longistics '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#03070a'
    - '#4c91d6'
    - '#7e7472'
    - '#feffff'
    - '#cf815a'
  brandStrength: 0.125
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
